apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: minecraft
data:
  EULA: "TRUE"
  LEVEL_NAME: "my-realm"        # must match extracted world folder name
  GAMEMODE: "survival"
  DIFFICULTY: "normal"
  MAX_PLAYERS: "3"
  SERVER_NAME: "Homelab SMP"
  ALLOW_CHEATS: "false"