apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  namespace: minecraft
spec:
  type: LoadBalancer
  selector:
    app: minecraft-bedrock
  ports:
    - port: 19132
      targetPort: 19132
      protocol: UDP