apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: kube-system
data:
  config.json: |-
    {
      "nodePathMap": [
        {
          "node": "monolith",
          "paths": [
            "/mnt/ssd-a"
          ]
        }
      ]
    }
